#!/usr/bin/env python3
"""merge_docs.py — ADDITIVE merge (never overwrite) for the LOCAL surfaces of
the target project (F5, docs/planning/00-plano-consolidado.md §5).

Real lesson that motivated this rule (captured in the lessons.md of the
reference donor harness): a `mv` that overwrote a canonical file without
checking whether it already existed. This module guarantees that pre-existing
CLAUDE.md/AGENTS.md are NEVER replaced whole, and that a pre-existing
settings.json has the harness hooks MERGED (not overwritten) with the hooks
the user already had.

Three strategies, by file type (B3, adversarial review post-v1.0.0: the
4 "sensitive" files of the brownfield flow are AGENTS.md, .claude/CLAUDE.md,
.claude/settings.json and .gitignore — the first 3 use the 2 strategies
below, .gitignore uses the 3rd):

  - Markdown (CLAUDE.md/AGENTS.md): marked block
    `<!-- orions-belt:begin (vX) -->` ... `<!-- orions-belt:end -->`.
    First install: the block is APPENDED to the end of the existing file (the
    user's content before the block is never touched). Reinstall/update:
    the CONTENT INSIDE the marked block is replaced (idempotent — it does not
    duplicate the block each round), the rest of the file stays untouched.

  - JSON (settings.json): structural merge per hook-event key —
    reconciliation by OWNERSHIP (A4, real gap: dedup by `command` alone
    was not enough — a matcher/timeout change on the SAME hook never landed,
    a hook removed upstream persisted, a rename left both entries
    registered). Ownership comes only from the exact command inventory stored
    by the prior install manifest; a path containing `.harness/hooks/` is not
    proof of ownership. The NEW side is the source of truth for that inventoried
    set, so update/removal/rename reconcile each round. On first adoption all
    preexisting commands are external, except an exact command also present in
    the new side (safe adoption/deduplication). Keys outside `hooks`
    (permissions, env, model, etc.) of the existing file are preserved.

  - .gitignore: same marked-block mechanism as Markdown, but with a
    `#` comment (not `<!-- -->`, which on a .gitignore line is not a
    comment — it becomes a literal ignore pattern starting with `<`).

CLI:
  merge_docs.py markdown --existing PATH --new PATH [--label TEXT]
      -> writes PATH with the merge applied (idempotent); prints JSON
         {"action": "created"|"appended"|"updated-block", "path": ...}
  merge_docs.py settings-json --existing PATH --new PATH
      [--owned-command EXACT_COMMAND ...]
      -> writes PATH with the merge applied; prints JSON
         {"action": "created"|"merged", "path": ..., "hooks_added": N,
          "hooks_kept": N, "hooks_removed_stale_owned": N,
          "keys_added": [non-hook top-level keys the template contributed]}
  merge_docs.py gitignore --existing PATH --new PATH [--label TEXT]
      -> writes PATH with the merge applied (idempotent); prints JSON
         {"action": "created"|"appended"|"updated-block", "path": ...}

Fail-open: if `--existing` does not exist, the behavior is "create from scratch"
(copies `--new` verbatim) — it is not an error.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# MARKER NAME (G7, adversarial review post-v1.0.0): renamed to
# `orions-belt:begin/end` to follow the product rename (see root README.md —
# the previous repo/product name became history in docs/planning/);
# the old marker only ever existed here in the framework's OWN code/tests,
# never in any real target project (product not yet published) — renaming
# does not break anyone's update idempotency. If this marker was ever
# written into a target project with the old name before this round,
# `merge_markdown` falls into the "no marked block yet" branch (BEGIN_RE does
# not match) and APPENDS a new block instead of updating the old one in-place —
# it loses no content, but duplicates the block once; documented here for transparency.
BEGIN_RE = re.compile(r"<!-- orions-belt:begin.*?-->", re.S)
END_MARK = "<!-- orions-belt:end -->"


def _marker_block(new_content: str, label: str) -> str:
    return (
        f"<!-- orions-belt:begin ({label}) — generated by orions-belt; "
        f"content between the markers is rewritten on every `harness-init`/`copier update`, "
        f"NEVER edit inside this block (the next round overwrites it). "
        f"Content ABOVE the block belongs to the project and is never touched. -->\n"
        f"{new_content.rstrip()}\n"
        f"{END_MARK}\n"
    )


def merge_markdown(existing_path: Path, new_path: Path, label: str) -> dict:
    new_content = new_path.read_text(encoding="utf-8")

    if not existing_path.exists():
        existing_path.parent.mkdir(parents=True, exist_ok=True)
        existing_path.write_text(_marker_block(new_content, label), encoding="utf-8")
        return {"action": "created", "path": str(existing_path)}

    existing_text = existing_path.read_text(encoding="utf-8")
    begin_match = BEGIN_RE.search(existing_text)
    end_idx = existing_text.find(END_MARK)

    if begin_match and end_idx != -1 and end_idx > begin_match.start():
        before = existing_text[: begin_match.start()]
        after = existing_text[end_idx + len(END_MARK):]
        prefix = before.rstrip()
        merged = prefix + ("\n\n" if prefix else "") + _marker_block(new_content, label) + after.lstrip("\n")
        existing_path.write_text(merged, encoding="utf-8")
        return {"action": "updated-block", "path": str(existing_path)}

    # no marked block yet -> APPEND to the end, never overwrite what already exists.
    merged = existing_text.rstrip() + "\n\n" + _marker_block(new_content, label)
    existing_path.write_text(merged, encoding="utf-8")
    return {"action": "appended", "path": str(existing_path)}


# --- .gitignore (B3, 4th sensitive file — same marked-block mechanics as
# Markdown, but with a `#` comment instead of `<!-- -->` because .gitignore is
# not HTML/Markdown and a raw `<!-- -->` comment would become a literal ignore
# PATTERN (a line starting with `<` is not a comment in .gitignore — only
# lines starting with `#` are). ---
GITIGNORE_BEGIN_RE = re.compile(r"^# orions-belt:begin.*$", re.M)
GITIGNORE_END_MARK = "# orions-belt:end"


def _gitignore_block(new_content: str, label: str) -> str:
    body = new_content.rstrip("\n")
    return (
        f"# orions-belt:begin ({label}) — generated by orions-belt; content between\n"
        f"# the markers is rewritten on every harness-install/copier update, do NOT edit\n"
        f"# inside this block. Lines ABOVE the block belong to the project and are never touched.\n"
        f"{body}\n"
        f"{GITIGNORE_END_MARK}\n"
    )


def merge_gitignore(existing_path: Path, new_path: Path, label: str) -> dict:
    new_content = new_path.read_text(encoding="utf-8")

    if not existing_path.exists():
        existing_path.parent.mkdir(parents=True, exist_ok=True)
        existing_path.write_text(_gitignore_block(new_content, label), encoding="utf-8")
        return {"action": "created", "path": str(existing_path)}

    existing_text = existing_path.read_text(encoding="utf-8")
    begin_match = GITIGNORE_BEGIN_RE.search(existing_text)
    end_idx = existing_text.find(GITIGNORE_END_MARK)

    if begin_match and end_idx != -1 and end_idx > begin_match.start():
        before = existing_text[: begin_match.start()]
        after = existing_text[end_idx + len(GITIGNORE_END_MARK):]
        prefix = before.rstrip("\n")
        merged = prefix + ("\n\n" if prefix else "") + _gitignore_block(new_content, label) + after.lstrip("\n")
        existing_path.write_text(merged, encoding="utf-8")
        return {"action": "updated-block", "path": str(existing_path)}

    # no marked block yet -> APPEND to the end, never overwrite what already exists.
    merged = existing_text.rstrip("\n") + "\n\n" + _gitignore_block(new_content, label)
    existing_path.write_text(merged, encoding="utf-8")
    return {"action": "appended", "path": str(existing_path)}


def _hook_command(entry: dict) -> str | None:
    return entry.get("command")


# A4 (adversarial review post-v1.0.0, real gap): the previous version deduped
# only by `command` string and ALWAYS preserved the old hook — 3 bad
# consequences: (1) an upstream matcher/timeout/statusMessage change on the SAME
# hook never landed (the identical command counted as "already registered", the
# old entry stayed frozen); (2) a hook removed in the new template (upstream
# decided to discontinue it) persisted forever in the target project; (3) a
# script rename (e.g. `foo.sh` -> `foo-v2.sh`) left BOTH entries registered
# (double-fire — the old hook is never removed because its command does not match
# the new one).
#
# Fix: reconciliation by EXPLICIT ownership inventory, never by a path-name
# heuristic. The installer persists the exact commands it last installed in
# `.harness/install-manifest.json`. In a reconciliation:
#   - every EXISTING entry whose exact command is in that prior inventory is
#     discarded (the newly rendered side reconciles update/removal/rename).
#   - every other EXISTING entry is external and always preserved, even when a
#     project intentionally keeps its own script under `.harness/hooks/`.
#   - on first adoption, an exact command also present in the new side is
#     adopted/deduplicated; no other preexisting command is claimed.
#   - all entries from the NEW side (always OWNED, by construction) are
#     inserted in full.
# Result: each merge round is a full reconciliation of the OWNED set
# (idempotent — running it twice does not duplicate, because round 2 discards and
# reinserts the same set), preserving the EXTERNAL set untouched.
def hook_identities(data: dict) -> set[str]:
    hooks = data.get("hooks", {})
    if not isinstance(hooks, dict):
        raise ValueError("settings hooks must be an object")
    identities: set[str] = set()
    for event, groups in hooks.items():
        if not isinstance(event, str) or not isinstance(groups, list):
            raise ValueError("settings hook events must map to lists")
        for group in groups:
            if not isinstance(group, dict) or not isinstance(group.get("hooks", []), list):
                raise ValueError("settings hook group must be an object with a hooks list")
            group_scope = {key: value for key, value in group.items() if key != "hooks"}
            for entry in group.get("hooks", []):
                if not isinstance(entry, dict):
                    raise ValueError("settings hook entries must be objects")
                command = _hook_command(entry)
                if isinstance(command, str) and command:
                    identities.add(json.dumps(
                        {"event": event, "group": group_scope, "command": command},
                        sort_keys=True, separators=(",", ":"), ensure_ascii=False,
                    ))
    return identities


def merge_settings_json(
    existing_path: Path,
    new_path: Path,
    previous_owned_identities: set[str] | None = None,
) -> dict:
    new_data = json.loads(new_path.read_text(encoding="utf-8"))
    new_owned_identities = hook_identities(new_data)
    prior_inventory = set(previous_owned_identities or ())

    if not existing_path.exists():
        existing_path.parent.mkdir(parents=True, exist_ok=True)
        # Canonical key order makes create -> first reconcile byte-idempotent.
        # JSON object order has no semantic meaning; preserving an incidental
        # source order here caused a one-time rewrite on the second install.
        existing_path.write_text(
            json.dumps(new_data, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        return {
            "action": "created", "path": str(existing_path),
            "hooks_added": 0, "hooks_kept": 0, "hooks_removed_stale_owned": 0,
            "keys_added": sorted(key for key in new_data if key != "hooks"),
        }

    existing_data = json.loads(existing_path.read_text(encoding="utf-8"))
    existing_hooks: dict = existing_data.get("hooks", {})
    new_hooks: dict = new_data.get("hooks", {})
    if not isinstance(existing_hooks, dict) or not isinstance(new_hooks, dict):
        raise ValueError("settings hooks must be an object")

    added = 0
    kept = 0
    removed_stale_owned = 0
    merged_hooks: dict = {}

    for event in sorted(set(existing_hooks) | set(new_hooks)):
        survivor_groups: list = []

        # 1) from the EXISTING side, keep only the EXTERNAL (non-owned) entries;
        #    OWNED entries are discarded here — the new side is what decides
        #    the final OWNED set (update/removal/rename resolved).
        existing_groups = existing_hooks.get(event, [])
        new_groups = new_hooks.get(event, [])
        if not isinstance(existing_groups, list) or not isinstance(new_groups, list):
            raise ValueError("settings hook events must map to lists")
        for matcher_group in existing_groups:
            if not isinstance(matcher_group, dict) or not isinstance(matcher_group.get("hooks", []), list):
                raise ValueError("settings hook group must be an object with a hooks list")
            group_hooks = matcher_group.get("hooks", [])
            group_scope = {key: value for key, value in matcher_group.items() if key != "hooks"}
            external_entries = []
            for hook in group_hooks:
                if not isinstance(hook, dict):
                    raise ValueError("settings hook entries must be objects")
                command = _hook_command(hook)
                identity = json.dumps(
                    {"event": event, "group": group_scope, "command": command},
                    sort_keys=True, separators=(",", ":"), ensure_ascii=False,
                )
                explicitly_owned = identity in prior_inventory
                exact_adoption = (
                    not prior_inventory
                    and isinstance(command, str)
                    and identity in new_owned_identities
                )
                if not explicitly_owned and not exact_adoption:
                    external_entries.append(hook)
            removed_stale_owned += len(group_hooks) - len(external_entries)
            kept += len(external_entries)
            if external_entries:
                merged_group = dict(matcher_group)
                merged_group["hooks"] = external_entries
                survivor_groups.append(merged_group)

        # 2) all entries from the NEW side (always owned, coming from the template
        #    rendered now) go in in full — the source of truth.
        for matcher_group in new_groups:
            if not isinstance(matcher_group, dict) or not isinstance(matcher_group.get("hooks", []), list):
                raise ValueError("settings hook group must be an object with a hooks list")
            new_entries = matcher_group.get("hooks", [])
            if new_entries:
                survivor_groups.append(dict(matcher_group))
                added += len(new_entries)

        if survivor_groups:
            merged_hooks[event] = survivor_groups

    merged_data = dict(existing_data)
    merged_data["hooks"] = merged_hooks

    # NON-HOOK KEYS (G-brownfield): the template may need settings.json keys
    # other than `hooks` — today `enabledPlugins`/`extraKnownMarketplaces`,
    # which declare the runtime plugin ENGINE a shipped rule set depends on
    # (the hookify rules were installed with no way to state their engine).
    # Before this, `merged_data = dict(existing_data)` plus rewriting only
    # `hooks` meant a new top-level key landed exclusively on the greenfield
    # `created` path and was SILENTLY DROPPED on every pre-existing file —
    # i.e. never on brownfield adoption, which is the installer's whole reason
    # to exist. The merge is strictly ADDITIVE and never destructive: a key
    # (or a nested entry) the project already declares always wins, so the
    # template can introduce a dependency without overwriting a local
    # decision — same contract the four shared surfaces already promise.
    keys_added: list[str] = []
    for key, new_value in new_data.items():
        if key == "hooks":
            continue
        current = merged_data.get(key)
        if key not in merged_data:
            merged_data[key] = new_value
            keys_added.append(key)
        elif isinstance(new_value, dict) and isinstance(current, dict):
            # entry-level union; the project's own entries take precedence
            merged_entry = {**new_value, **current}
            if merged_entry != current:
                merged_data[key] = merged_entry
                keys_added.append(key)

    existing_path.write_text(
        json.dumps(merged_data, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return {
        "action": "merged", "path": str(existing_path),
        "hooks_added": added, "hooks_kept": kept, "hooks_removed_stale_owned": removed_stale_owned,
        "keys_added": sorted(keys_added),
    }


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)

    p_md = sub.add_parser("markdown")
    p_md.add_argument("--existing", required=True, type=Path)
    p_md.add_argument("--new", required=True, type=Path)
    p_md.add_argument("--label", default="harness-init")

    p_json = sub.add_parser("settings-json")
    p_json.add_argument("--existing", required=True, type=Path)
    p_json.add_argument("--new", required=True, type=Path)
    p_json.add_argument("--owned-command", action="append", default=[])

    p_gi = sub.add_parser("gitignore")
    p_gi.add_argument("--existing", required=True, type=Path)
    p_gi.add_argument("--new", required=True, type=Path)
    p_gi.add_argument("--label", default="harness-init")

    args = ap.parse_args(argv)

    if args.cmd == "markdown":
        result = merge_markdown(args.existing, args.new, args.label)
    elif args.cmd == "gitignore":
        result = merge_gitignore(args.existing, args.new, args.label)
    else:
        prior_identities: set[str] = set()
        if args.owned_command and args.existing.exists():
            # Legacy/manual CLI compatibility only. The stateful installer
            # persists structural identities and never uses this command-only
            # selector.
            existing_data = json.loads(args.existing.read_text(encoding="utf-8"))
            for identity in hook_identities(existing_data):
                decoded = json.loads(identity)
                if decoded.get("command") in set(args.owned_command):
                    prior_identities.add(identity)
        result = merge_settings_json(args.existing, args.new, prior_identities)

    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
